[RunControl]
NEVENTS = 100

[Producer.ASTROPIXv3_0]
EUDAQ_DC = dc
EUDAQ_ID = 0

[Producer.ASTROPIXv3_1]
EUDAQ_DC = dc
EUDAQ_ID = 1

[DataCollector.dc]
EUDAQ_FW = native
EUDAQ_FW_PATTERN = /tmp/run$6R_$12D$X

